# Generated by Django 2.2 on 2023-12-17 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechTown', '0002_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedailyreport',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
